name: CI_final

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Environment to deploy to'
        required: true
        options:
          - prod
          - stg
  push:
    branches:
      # which branch changes will deploy the code
      - actions_test

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint

    - name: Run unit tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Run integration tests
      run: npm run test:integration

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to production
      run: |
        # Add your deployment script here
        echo "Deploying to production..."
